#!/bin/sh

if [ -z $XDG_CURRENT_DESKTOP ]; then
  export XDG_CURRENT_DESKTOP="GNOME-Flashback:GNOME"
fi

exec compton & gnome-session --systemd --session=gnome-flashback-xmonad --disable-acceleration-check "$@"

